# Generated by Django 4.2.7 on 2023-11-27 17:20

import django.core.validators
from django.db import migrations, models
import student_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
        ('student_app', '0004_alter_student_locker_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(default=None, related_name='enrolled_students', to='subject_app.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', validators=[student_app.validators.validate_combination_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default=110, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', validators=[student_app.validators.validate_name_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='student@school.com', max_length=254, unique=True, validators=[student_app.validators.validate_school_email]),
        ),
    ]
